### ISSUE TITLE
Any plans to handle HA namenodes?

### ISSUE THREAD

**Issue by lordjc** [pywebhdfs/pywebhdfs#19]

**Comment by stevendgonzales** [comment]
Would this be described as:
accepting a list of name nodes
attempting to failover to other name node on error
keeping cache of last good namenode used

?

**Comment by lordjc** [comment]
Yes for the most part.
It looks like Hue is just pulling the list from the config.
https://github.com/cloudera/hue/blob/master/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py#L844

**Comment by stevendgonzales** [comment]
That method does not look like it is using multiple host:port.  However, HA name ode does seem like a good feature.  I will leave this issue open.

**Comment by cloverrose** [comment]
Hi, related to this issue I want to know, do you have any plans to handle namenode federation?

**Comment by stevendgonzales** [comment]
Not at the moment but we would gladly accept a pull request. Do you have
any ideas of how to implement that?

**Comment by cloverrose** [comment]
@stevendgonzales This issue can be closed
