### ISSUE TITLE
Errno 115

### ISSUE THREAD

**Issue by okleber** [pywebhdfs/pywebhdfs#34]
I was trying to use pywebhdfs for the first time.
I got this on my firt attempt.

requests.exceptions.ConnectionError: HTTPConnectionPool(host='quickstart.clouder                                                                                        a', port=50070): Max retries exceeded with url: /webhdfs/v1/user/hdfs/myfile.txt                                                                                        ?op=CREATE&user.name=hdfs (Caused by NewConnectionError('<requests.packages.urll                                                                                        ib3.connection.HTTPConnection object at 0xba96d0>: Failed to establish a new con                                                                                        nection: [Errno 115] Operation now in progress',))

I found this thread:
https://github.com/kennethreitz/requests/issues/2699

I change this:
/usr/lib/python2.6/site-packages/pywebhdfs/webhdfs.py
-def __init__(self, host='localhost', port='50070', user_name=None,path_to_hosts=None, timeout=0):
+def __init__(self, host='localhost', port='50070', user_name=None,path_to_hosts=None, timeout=None):

For write is working. What I need for now. Is not a issue on pywebhdfs, but I think this will help others. I din´t find another place to put this information. Sorry

**Comment by stevendgonzales** [comment]
default timeout value is now None
