### ISSUE TITLE
Comments on pull request 36?

### ISSUE THREAD

**Issue by patvarilly** [pywebhdfs/pywebhdfs#37]
Hi,

I made a pull request a couple of weeks ago (https://github.com/pywebhdfs/pywebhdfs/pull/36) to support using pywebhdfs through a secure web proxy like Knox.  Any thoughts?  I work on a project that uses this modified version of pywebhdfs, and for ease of maintainability, we'd love to download an improved official release of pywebhdfs instead of using an internally patched package.

Thanks,

Patrick

**Comment by stevendgonzales** [comment]
Merged, thank you for the contribution
