### ISSUE TITLE
Respect proxy environment variable

### ISSUE THREAD

**Issue by sztanko** [pywebhdfs/pywebhdfs#38]
We had an issue installing this package on a machine that communicates with outer world via an http(s) proxy. Package pbr could not be installed.

It seems like code here
https://github.com/pywebhdfs/pywebhdfs/blob/master/setup.py is not taking into the account the existence of the proxy environment variable, as pip does.

**Comment by expobrain** [comment]
Looks like the issue is in `setuptools`, see this thread's comment https://github.com/pypa/pip/issues/3478#issuecomment-182865225

The current workaround is to download and install `pbr` before `pywebhdfs`, which by the way is not ideal.
