### ISSUE TITLE
hdfs.read_file is giving exception , every other command is working fine , only on reading error

### ISSUE THREAD

**Issue by matesio** [pywebhdfs/pywebhdfs#54]
Reading file from hadoop hdfs
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 35.154.212.149
Traceback (most recent call last):
  File "list.py", line 20, in <module>
    file_data = hdfs.read_file("user/hduser/sample/file.txt")
Reading file from hadoop hdfs
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 35.154.212.149
Traceback (most recent call last):
  File "list.py", line 20, in <module>
    file_data = hdfs.read_file("user/hduser/sample/file.txt")

raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='35.154.212.149', port=54310): Max retries exceeded with url: /webhdfs/v1/user/hduser/sample/file.txt?op=OPEN&user.name=hduser (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f3764480850>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by ghost** [comment]
I got the same error , did you solve it ?

**Comment by matesio** [comment]
@mysteryHJJ , i was using  hadoop on hortonwroks, i changed df.namenode.http-address bind to 0.0.0.0:50070 , and my error was gone.
