### ISSUE TITLE
Add Python 3 support

### ISSUE THREAD

**Issue by chadlung** [pywebhdfs/pywebhdfs#6]
I believe there is some work to be done in regards to the httplib import, but that is it.

Need to modify tox and Travis then to support py3 as well as the current 2.7.x.

**Comment by airhorns** [comment]
Is anyone working on this?

**Comment by jmvrbanac** [comment]
@airhorns not yet iirc. If you're looking for an issue to pick up, this is a great one to work on :) .

**Comment by chadlung** [comment]
Closed with PR: https://github.com/pywebhdfs/pywebhdfs/pull/18
